{"name": "Проверка изменения данных неавторизованного пользователя", "status": "passed", "start": 1730575350403, "stop": 1730575351159, "uuid": "1b8c9481-85dd-4f20-a7e6-32d7c0e03b04", "historyId": "a135e41341265b8a09b8058e07f8127e", "testCaseId": "a135e41341265b8a09b8058e07f8127e", "fullName": "tests.test_update_user.TestUpdateUser#test_update_unauthorized_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "DESKTOP-4QJCJVN"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user"}]}